<?php
/**
 * VerySimpleLinkCollection.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleLinkCollection
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Item selector plugin implementation class.
 */
class VerySimpleLinkCollection_Form_Plugin_ItemSelector extends VerySimpleLinkCollection_Form_Plugin_Base_ItemSelector
{
    // feel free to add your customisation here
}
