<?php
/**
 * VerySimpleLinkCollection.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleLinkCollection
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class VerySimpleLinkCollection_TaggedObjectMeta_VerySimpleLinkCollection extends VerySimpleLinkCollection_TaggedObjectMeta_Base_VerySimpleLinkCollection
{
    // feel free to extend the tag support here
}
