<?php
/**
 * VerySimpleLinkCollection.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleLinkCollection
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de) at Sun Mar 16 16:48:11 CET 2014.
 */

/**
 * Version information implementation class.
 */
class VerySimpleLinkCollection_Version extends VerySimpleLinkCollection_Base_Version
{
    // custom enhancements can go here
}
