<?php
/**
 * VerySimpleLinkCollection.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleLinkCollection
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This is the Admin controller class providing navigation and interaction functionality.
 */
class VerySimpleLinkCollection_Controller_Admin extends VerySimpleLinkCollection_Controller_Base_Admin
{
    // feel free to add your own controller methods here
}
